export const QUIZ_DETAILS_REQUEST = 'QUIZ_DETAILS_REQUEST'
export const QUIZ_DETAILS_SUCCESS = 'QUIZ_DETAILS_SUCCESS'
export const QUIZ_DETAILS_FAIL = 'QUIZ_DETAILS_FAIL'
export const QUIZ_DETAILS_RESET = 'QUIZ_DETAILS_RESET'

