export const TICTOE_REQUEST = 'TICTOE_REQUEST'
export const TICTOE_SUCCESS = 'TICTOE_SUCCESS'
export const TICTOE_FAIL = 'TICTOE_FAIL'

export const QUIZ_REQUEST = 'QUIZ_REQUEST'
export const QUIZ_SUCCESS = 'QUIZ_SUCCESS'
export const QUIZ_FAIL = 'QUIZ_FAIL'
export const QUIZ_RESET = 'QUIZ_RESET'

